apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-st5p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-st5p
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-st5p
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-st5p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-st5p
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-liua-tenant/rhtap-demo-app/hacbs-test-project-st5p@sha256:46085f7b1b0d6790adb6019b06249fc389e6aa88e4b0e978eeac759e1393ffc0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
